### ISSUE TITLE
SMS okay cannot call

### ISSUE THREAD

**Issue by cleidigh** [techno-express/minigooglevoice#1]
@techno-express 
Thanks for your suggestion on the other repository.
I pulled in your Googlevoice module and also took your gvcall.py and your message files.  
I wanted to use the simplest thing possible.
Login works fine as you can see in sending an SMS does as well see the console output below.
the call fails still.  anything popout in terms of my parameters?
any suggestions?  I cannot run your PHP since I don't have anything set up for it but I don't think that's necessary.
Note:  I have my Google voice set up to allow less secure apps and I have done reset many times.

Thanks

C:\Users\Christopher Leidigh\Dropbox\Python\pygooglevoice>Python gvsms.py cleidigh@Gmail.com [psw] 4019656105 hello
Message Sent

C:\Users\Christopher Leidigh\Dropbox\Python\pygooglevoice>Python gvcall.py cleidigh@Gmail.com [psw] 4014213301 4018304055 9
Error! Calling failed

C:\Users\Christopher Leidigh\Dropbox\Python\pygooglevoice>

**Comment by cleidigh** [comment]
@techno-express 
I'm wondering if I need credit for this type of use , I have zero dollars now.

I have a bit more anecdotal data:
- the Google voice webpage works I can make a phone call through my cell phone or "GoogleHangOuts"
- if I try the chrome Web store app I can only call through the cell phone using "GoogleTalk" fails
that application is quite old

**Comment by TheTechsTech** [comment]
Need to investigate more, I call make call using the web/php app project. I just tried. But I do get the same error trying gvcall.py at command line. That's strange, the web/php is call/running that script to actually make the call.

**Comment by TheTechsTech** [comment]
ok, you need to add +1 to the forwarding number. i looked at the gvconfig.php setting file. my call was made when that was added. 
Try:
C:\Users\Christopher Leidigh\Dropbox\Python\pygooglevoice>Python gvcall.py cleidigh@Gmail.com [psw] 4014213301 +14018304055 9

Try that with gvoice too see what you get.

**Comment by cleidigh** [comment]
@techno-express 
Thanks, I have some progress 

The +1 on the forwarding number does make a difference.  The problem  is when trying to use the Google voice number as the forwarding number.  I want to do a direct call from the Windows PC using the command line  or Python application to any arbitrary number without calling through the cell phone
which I cannot use since I am disabled.

In the examples below:

4019656105 - Mobile phone 
4018304055 - My Google voice number
4015213770 - normal landline phone

The following works but the initial call is placed with the cell phone - useless to me
Python gvcall.py cleidigh@Gmail.com [password] 4015213770 +14019656105 2

The following fails when trying to use the Google voice number to call out - this is what I want
Doing this combination of numbers does work in Chrome on the Google voice page.

Python gvcall.py cleidigh@Gmail.com [password] 4015213770 +14018304055 9

in order to make the above work there has to be both microphone and speaker support within the Google voice Python module and there would have to be follow-on code after the call is dialed
to support the call duration.  I don't see anything the library that implies that type of support.
maybe this is only possible through the Google voice Web interface?

**Comment by TheTechsTech** [comment]
now speak of a whole different issue. what you what is a pbx system like freepbx - asterisk base. this package and all forks is setup to make/start the call, which is completed by connecting to an actual phone you have. i i have my freepbx setup that does what you actually want. 

what you currently trying to do is not going to work as you envision. it has to go thru some phone if not using an pbx setup.
